#!/usr/bin/env bash

echo -e "\nPHPLINT src/:"
find src/ -iname "*.php" -print0 | xargs -0 -n1 -P4 php -l 1>/dev/null
echo -e "\nPHPLINT tests/:"
find tests/ -iname "*.php" -print0 | xargs -0 -n1 -P4 php -l 1>/dev/null
echo -e "\nPHPUNIT:"
phpunit --stop-on-error --stop-on-failure
echo -e "\nPHPCS src/:"
phpcs --warning-severity=0 --standard=PSR2 src/ 
echo -e "\nPHPCS tests/:"
phpcs --warning-severity=0 --standard=PSR2 tests/
echo -e "\nPHPMD src/:"
phpmd src/ text phpmd.xml
echo -e "\nPHPMD tests/:"
phpmd tests/ text phpmd-tests.xml

